# Generated by Django 5.2.3 on 2025-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncall',
            name='best_time_for_collection',
        ),
        migrations.AddField(
            model_name='collectioncall',
            name='best_time_for_collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Melhor Data para Coleta'),
        ),
        migrations.AddField(
            model_name='collectioncall',
            name='best_time_for_collection_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Melhor Hora para Coleta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('app', 'Aplicativo'), ('web', 'Web')], default='app', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
