# Generated by Django 5.2.3 on 2025-08-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_collectioncall_best_time_for_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncall',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Resíduo'),
        ),
    ]
