# Generated by Django 5.2.3 on 2025-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collectioncall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncall',
            name='best_time_for_collection_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Melhor Horário para Coleta'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizada'), ('failed', 'Cancelada')], default='pending', max_length=50, verbose_name='Status do Chamado'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='type',
            field=models.CharField(blank=True, choices=[('paper', 'Papel'), ('metal', 'Metal'), ('plastic', 'Plástico'), ('electronic', 'Eletrônico'), ('organic', 'Orgânico'), ('glass', 'Vidro'), ('residual_waste', 'Resíduo Sólido'), ('other', 'Outro')], null=True, verbose_name='Tipo de Resíduo'),
        ),
    ]
