# Generated by Django 5.2.3 on 2025-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_collectioncall_best_time_for_collection_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncall',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizada'), ('failed', 'Cancelada')], default='pending', verbose_name='Status do Chamado'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='urgency',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Moderada'), ('high', 'Alta')], default='low', verbose_name='Urgência do Chamado'),
        ),
    ]
