# Generated by Django 5.2.3 on 2025-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collectioncall_address_alter_collectioncall_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncall',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='type',
            field=models.CharField(choices=[('paper', 'Papel'), ('metal', 'Metal'), ('plastic', 'Plástico'), ('electronic', 'Eletrônico'), ('organic', 'Orgânico'), ('glass', 'Vidro'), ('residual_waste', 'Resíduo Sólido'), ('other', 'Outro')], default='other', verbose_name='Tipo de Resíduo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Número de Telefone'),
        ),
    ]
