# Generated by Django 5.2.3 on 2025-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_collectioncall_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioncall',
            old_name='amount_to_collected',
            new_name='amount_to_collect',
        ),
        migrations.RemoveField(
            model_name='collectioncall',
            name='best_time_for_collection_date',
        ),
        migrations.RemoveField(
            model_name='collectioncall',
            name='best_time_for_collection_time',
        ),
        migrations.AddField(
            model_name='collectioncall',
            name='best_time_for_collect',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Melhor Data/Horário para Coleta'),
        ),
    ]
