# Generated by Django 5.2.3 on 2025-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_amount_to_collected_collectioncall_amount_to_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Telefone'),
        ),
    ]
