# Generated by Django 5.2.3 on 2025-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizada'), ('failed', 'Cancelada'), ('in_process', 'Em Andamento')], default='pending', verbose_name='Status do Chamado'),
        ),
        migrations.AlterField(
            model_name='collectioncall',
            name='type',
            field=models.CharField(choices=[('paper', 'Papel'), ('metal', 'Metal'), ('plastic', 'Plástico'), ('electronic', 'Eletrônico'), ('organic', 'Orgânico'), ('glass', 'Vidro'), ('residual_waste', 'Rejeito'), ('other', 'Outro')], default='other', verbose_name='Tipo de Resíduo'),
        ),
    ]
