# Generated by Django 5.2.3 on 2025-07-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioncall',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chamado de Coleta', 'verbose_name_plural': 'Chamados de Coleta'},
        ),
        migrations.RenameField(
            model_name='collectioncall',
            old_name='call_date',
            new_name='created_at',
        ),
    ]
